language: node
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
  - sudo apt-get -qq update
  - sudo apt-get install -y tzdata php5
before_script:
  - npm install
  - npm install -g bower
  - bower install
  - sudo apt-get update -qq
  - sudo apt-get install -y php5-cli
script:
  - grunt
  - grunt coveralls
